### PR TITLE
Checkout after editing shipping address/method.

### PR DESCRIPTION
**Pull request by devpatil7**
Extended test and also updated test case ID's for ongoing release.

Test on PR-2365 deployed instance https://pr-2365.pwa-venia.com/ ... (If the PR is merged then this can be tested on https://develop.pwa-venia.com/)

Verification - 
1. `CartPageEditProductAndCheckout` and `CartPageGuestCheckout` should Pass.

### CODE REVIEW

**Comment by revanth0212** [comment]
`CartPageEditProductAndCheckout` test failed with the following error

image

**Comment by revanth0212** [comment]
Also `CartPageGuestCheckout` failed with a similar error. I have docker running.

These look like they are connected, like something I am missing.

image

**Comment by devpatil7** [comment]
@revanth0212 Dialogue component css was updated after i completed this ticket. Should be good now.

**Comment by devpatil7** [comment]
@revanth0212  Intermittentantly backend is getting slow so you might hit error on click on Review order or Place order. I ran entire suite and here are the results - 

image


image

**Review by revanth0212 — APPROVED** [review]

**Pull request merged**
